### ISSUE TITLE
Build issue 

### ISSUE THREAD

**Issue by cooligc** [rmpestano/cdi-crud#2]
Hi 

After checking this out , I am not able to build the application with following branches

 remotes/origin/cdi-crud-it
  remotes/origin/cdi-crud-services
  remotes/origin/cdi-crud-universe
  remotes/origin/gatling-jsf-issue
  remotes/origin/master

Can you please merge the latest working changes to master , So that it'll helpful for other to refer this example?

Thanks!
sitakant

**Comment by rmpestano** [comment]
Hi @cooligc,

what issues are you having? 

Its working for me and on [travisci](https://travis-ci.org/rmpestano/cdi-crud).

What is the output for the maven command below?

```
mvn clean package
```
